name: flutter_di_things
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  path: ^1.8.2
  json_annotation: ^4.7.0
  dio: ^4.0.6
  injectable: ^1.5.4
  get_it: ^7.2.0
  retrofit: ^3.3.1
  rxdart: ^0.27.5
  loading_overlay: ^0.3.0
  logger: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.5
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  retrofit_generator: ^4.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/env/


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
